# CRD configuration
crds:
  enabled: true
  upgradeStrategy: "manual"  # manual | auto

# Webhook configuration
webhooks:
  enabled: true

# Resource interpreters configuration
resourceInterpreters:
  queueEnabled: true
  jobEnabled: true

# Propagation policies configuration
propagationPolicies:
  enabled: true
  deletionProtection: false
