apiVersion: v1
description: A Helm chart for Volcano Global
name: volcano-global
version: "1.0.0"
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/volcano-sh/charts/master/docs/images/volcano-logo.png
home: https://volcano.sh
sources:
  - https://github.com/volcano-sh/volcano-global
maintainers:
  - name: volcano-global-maintainers
    email: volcano-global@volcano.sh
