apiVersion: v1
kind: ServiceAccount
metadata:
  name: volcano-global-webhook-init-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: volcano-global-admission-init
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volcano-global-webhook-init-clusterrole
  labels:
    app: volcano-global-admission-init
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create", "list", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volcano-global-webhook-init-clusterrolebinding
  labels:
    app: volcano-global-admission-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volcano-global-webhook-init-clusterrole
subjects:
  - kind: ServiceAccount
    name: volcano-global-webhook-init-sa
    namespace: {{ .Release.Namespace }}
