{{- if .Values.custom.controller_enable }}
{{ $controller_affinity := or .Values.custom.controller_affinity .Values.custom.default_affinity }}
{{ $controller_tolerations := or .Values.custom.controller_tolerations .Values.custom.default_tolerations }}
{{ $controller_sc := or .Values.custom.controller_sc .Values.custom.default_sc }}
{{ $controller_main_csc := or .Values.custom.controller_main_csc .Values.custom.default_csc }}
{{ $controller_ns := or .Values.custom.controller_ns .Values.custom.default_ns }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volcano-global-controller-manager
  namespace: {{ .Release.Namespace }}
  {{- if or (.Values.custom.controller_labels) (.Values.custom.common_labels) }}
  labels:
    {{- mustMerge (.Values.custom.controller_labels | default (dict)) (.Values.custom.common_labels | default (dict)) | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.custom.controller_replicas }}
  selector:
    matchLabels:
      app: volcano-global-controller-manager
  template:
    metadata:
      labels:
        app: volcano-global-controller-manager
        {{- if .Values.custom.controller_podLabels }}
        {{- toYaml .Values.custom.controller_podLabels | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- if $controller_tolerations }}
      tolerations:
        {{- toYaml $controller_tolerations | nindent 8 }}
      {{- end }}
      {{- if $controller_ns }}
      nodeSelector:
        {{- toYaml $controller_ns | nindent 8 }}
      {{- end }}
      {{- if $controller_affinity }}
      affinity:
        {{- toYaml $controller_affinity | nindent 8 }}
      {{- end }}
      {{- if $controller_sc }}
      securityContext:
        {{- toYaml $controller_sc | nindent 8 }}
      {{- end }}
      {{- if .Values.basic.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.basic.image_pull_secret }}
      {{- end }}
      containers:
        - name: volcano-global-controllers-manager
          image: {{ .Values.basic.image_registry }}/{{ .Values.basic.controller_image_name }}:{{ .Values.basic.image_tag_version }}
          imagePullPolicy: {{ .Values.basic.image_pull_policy }}
          args:
            - --kubeconfig={{ .Values.basic.karmada_kubeconfig_path }}
            {{- if .Values.custom.leader_elect_enable }}
            - --leader-elect=true
            {{- else }}
            - --leader-elect=false
            {{- end }}
            - --leader-elect-resource-namespace={{ .Values.custom.leader_elect_resource_namespace }}
            - --logtostderr
            {{- if .Values.custom.enable_healthz }}
            - --enable-healthz=true
            - --healthz-address=$(MY_POD_IP):{{ .Values.custom.healthz_port }}
            - --listen-address=$(MY_POD_IP):9090
            {{- end }}
            - --dispatch-period={{ .Values.custom.dispatch_period }}
            - --controllers={{ .Values.custom.controllers }}
            {{- if .Values.custom.reconcilers }}
            - --reconcilers={{ .Values.custom.reconcilers }}
            {{- end }}
            {{- if .Values.custom.feature_gates }}
            - --feature-gates={{ .Values.custom.feature_gates }}
            {{- end }}
            - -v={{ .Values.custom.controller_log_level }}
            - 2>&1
          {{- if $controller_main_csc }}
          securityContext:
            {{- toYaml $controller_main_csc | nindent 12 }}
          {{- end }}
          {{- if .Values.custom.controller_resources }}
          resources:
            {{- toYaml .Values.custom.controller_resources | nindent 12 }}
          {{- end }}
          {{- if .Values.custom.enable_healthz }}
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            httpGet:
              path: /healthz
              port: {{ .Values.custom.healthz_port }}
              scheme: HTTP
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            httpGet:
              path: /healthz
              port: {{ .Values.custom.healthz_port }}
              scheme: HTTP
            timeoutSeconds: 5
          {{- end }}
          volumeMounts:
            - name: webhook-config
              mountPath: /etc/kubeconfig
              readOnly: true
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      volumes:
        - name: webhook-config
          secret:
            secretName: {{ .Values.basic.karmada_kubeconfig_secret_name }}
{{- end }}
