{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "volcano-global.namespace" . }}
  labels:
    {{- include "volcano-global.labels" . | nindent 4 }}
{{- end }}
