{{- if .Values.custom.webhook_enable }}
{{ $webhook_affinity := or .Values.custom.webhook_affinity .Values.custom.default_affinity }}
{{ $webhook_tolerations := or .Values.custom.webhook_tolerations .Values.custom.default_tolerations }}
{{ $webhook_sc := or .Values.custom.webhook_sc .Values.custom.default_sc }}
{{ $webhook_main_csc := or .Values.custom.webhook_main_csc .Values.custom.default_csc }}
{{ $webhook_init_csc := or .Values.custom.webhook_init_csc .Values.custom.default_csc }}
{{ $webhook_ns := or .Values.custom.webhook_ns .Values.custom.default_ns }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: volcano-global-webhook-manager
    {{- if or (.Values.custom.webhook_labels) (.Values.custom.common_labels) }}
    {{- mustMerge (.Values.custom.webhook_labels | default (dict)) (.Values.custom.common_labels | default (dict)) | toYaml | nindent 4 }}
    {{- end }}
  name: volcano-global-webhook-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.custom.webhook_replicas }}
  selector:
    matchLabels:
      app: volcano-global-webhook-manager
  template:
    metadata:
      labels:
        app: volcano-global-webhook-manager
        {{- if .Values.custom.webhook_podLabels }}
        {{- toYaml .Values.custom.webhook_podLabels | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- if $webhook_tolerations }}
      tolerations:
        {{- toYaml $webhook_tolerations | nindent 8 }}
      {{- end }}
      {{- if $webhook_ns }}
      nodeSelector:
        {{- toYaml $webhook_ns | nindent 8 }}
      {{- end }}
      {{- if $webhook_affinity }}
      affinity:
        {{- toYaml $webhook_affinity | nindent 8 }}
      {{- end }}
      {{- if $webhook_sc }}
      securityContext:
        {{- toYaml $webhook_sc | nindent 8 }}
      {{- end }}
      {{- if .Values.basic.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.basic.image_pull_secret }}
      {{- end }}
      containers:
        - name: volcano-global-webhook-manager
          args:
            - --kubeconfig={{ .Values.basic.karmada_kubeconfig_path }}
            - --enabled-admission={{ .Values.custom.enabled_admissions }}
            - --tls-cert-file=/admission.local.config/certificates/tls.crt
            - --tls-private-key-file=/admission.local.config/certificates/tls.key
            - --ca-cert-file=/admission.local.config/certificates/ca.crt
            - --webhook-service-name={{ .Values.basic.webhook_service_name }}
            - --webhook-namespace={{ .Release.Namespace }}
            - --logtostderr
            {{- if .Values.custom.enable_healthz }}
            - --enable-healthz=true
            - --healthz-address=$(MY_POD_IP):{{ .Values.custom.healthz_port }}
            - --listen-address=$(MY_POD_IP)
            {{- end }}
            - --port={{ .Values.custom.webhook_port }}
            - -v={{ .Values.custom.webhook_log_level }}
            - 2>&1
          image: {{ .Values.basic.image_registry }}/{{ .Values.basic.webhook_image_name }}:{{ .Values.basic.image_tag_version }}
          imagePullPolicy: {{ .Values.basic.image_pull_policy }}
          {{- if $webhook_main_csc }}
          securityContext:
            {{- toYaml $webhook_main_csc | nindent 12 }}
          {{- end }}
          {{- if .Values.custom.webhook_resources }}
          resources:
            {{- toYaml .Values.custom.webhook_resources | nindent 12 }}
          {{- end }}
          {{- if .Values.custom.enable_healthz }}
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            httpGet:
              path: /healthz
              port: {{ .Values.custom.healthz_port }}
              scheme: HTTPS
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            httpGet:
              path: /healthz
              port: {{ .Values.custom.healthz_port }}
              scheme: HTTPS
            timeoutSeconds: 5
          {{- end }}
          volumeMounts:
            - mountPath: /admission.local.config/certificates
              name: admission-certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/kubeconfig
              readOnly: true
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      volumes:
        - name: webhook-config
          secret:
            secretName: {{ .Values.basic.karmada_kubeconfig_secret_name }}
        - name: admission-certs
          secret:
            secretName: {{ .Values.basic.webhook_secret_name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.basic.webhook_service_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: volcano-global-webhook-manager
    {{- if .Values.custom.common_labels }}
    {{- toYaml .Values.custom.common_labels | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.custom.webhook_port }}
  selector:
    app: volcano-global-webhook-manager
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml .Values.service.ipFamilies | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volcano-global-webhook-init-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: volcano-global-admission-init
    {{- if .Values.custom.common_labels }}
    {{- toYaml .Values.custom.common_labels | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volcano-global-webhook-init-clusterrole
  labels:
    app: volcano-global-admission-init
    {{- if .Values.custom.common_labels }}
    {{- toYaml .Values.custom.common_labels | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "create", "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volcano-global-webhook-init-clusterrolebinding
  labels:
    app: volcano-global-admission-init
    {{- if .Values.custom.common_labels }}
    {{- toYaml .Values.custom.common_labels | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volcano-global-webhook-init-clusterrole
subjects:
  - kind: ServiceAccount
    name: volcano-global-webhook-init-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: volcano-global-admission-init
  namespace: {{ .Release.Namespace }}
  labels:
    app: volcano-global-admission-init
    {{- if .Values.custom.common_labels }}
    {{- toYaml .Values.custom.common_labels | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "5"
spec:
  backoffLimit: 3
  template:
    spec:
      {{- if $webhook_tolerations }}
      tolerations:
        {{- toYaml $webhook_tolerations | nindent 8 }}
      {{- end }}
      {{- if $webhook_ns }}
      nodeSelector:
        {{- toYaml $webhook_ns | nindent 8 }}
      {{- end }}
      {{- if $webhook_affinity }}
      affinity:
        {{- toYaml $webhook_affinity | nindent 8 }}
      {{- end }}
      {{- if $webhook_sc }}
      securityContext:
        {{- toYaml $webhook_sc | nindent 8 }}
      {{- end }}
      serviceAccountName: volcano-global-webhook-init-sa
      {{- if .Values.basic.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.basic.image_pull_secret }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: main
          image: {{ .Values.basic.image_registry }}/{{ .Values.basic.webhook_image_name }}:{{ .Values.basic.image_tag_version }}
          imagePullPolicy: {{ .Values.basic.image_pull_policy }}
          command: ["./gen-admission-secret.sh", "--service", "{{ .Values.basic.webhook_service_name }}", "--namespace",
                    "{{ .Release.Namespace }}", "--secret", "{{ .Values.basic.webhook_secret_name }}"]
          {{- if $webhook_init_csc }}
          securityContext:
            {{- toYaml $webhook_init_csc | nindent 12 }}
          {{- end }}
          {{- if .Values.custom.webhook_resources }}
          resources:
            {{- toYaml .Values.custom.webhook_resources | nindent 12 }}
          {{- end }}
{{- end }}
